---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_facts:
      cloud: ospcloud
    register: servers

  - name: Delete instances
    os_server:
        name: "{{ item.name }}"
        state: absent
    loop: "{{ openstack_servers }}"
