- hosts: workstation
#  become: yes
  tasks:
  - name: create frontend instance
    include_role:
      name: osp-servers
      vars_from: frontend.yml
  - name: create app instance
    include_role:
      name: osp-servers
      vars_from: app.yml
  - name: create db instance
    include_role:
      name: osp-servers
      vars_from: db.yml
