- hosts: workstation
#  become: yes
  tasks:
  - name: include var from role osp-servers
    include_vars:
      file: ./roles/osp-servers/vars/main.yml 
      name: all_servers

  - debug:
      var: all_servers
  #  loop: "{ all_servers }"
