---

# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server: 
    state: present 
    name: "{{ item.value.name }}" 
    image: "{{ item.value.image }}"
    key_name: "{{ item.value.key_name }}" 
    wait: yes
    flavor: "{{ item.value.flavor }}"
    network: int_network
    security_groups: "{{ item.value.security_group }}"
    meta:
      group: "{{ item.value.meta.group }}"
      deployment_name: "{{ item.value.meta.deployment_name }}"
  register: instanceipaddr

- name: Add floating IP to Servers
  os_floating_ip:
    state: present
    server: "{{ item.value.name }}"
    network: ext_network
    wait: true
    timeout: 180
  register: instanceipfloat

- name: Show "{{ instanceipaddr }}" EXT IP
  debug: var=instanceipfloat.floating_ip.floating_ip_address

- name: Wait for server to be available
  wait_for:
    host: "{{ instanceipfloat.floating_ip.floating_ip_address }}"
    port: 22
    search_regex: SSH
    timeout: 600
