---

# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server: 
    state: present 
    name: "{{ instance_name }}" 
    image: "rhel-guest"
    key_name: ansible_ssh
    wait: yes
    flavor: m2.small
    network: int_network
    security_groups: "{{ security_group_name }}"
    meta:
      group: "{{ group }}"
      deployment_name: "{{ deployment }}"
  register: instanceipaddr

- name: Add floating IP to Servers
  os_floating_ip:
    state: present
    server: "{{ instance_name }}"
    network: ext_network
    wait: true
    timeout: 180
  register: instanceipfloat

- name: Show "{{ instanceipaddr }}" EXT IP
  debug: var=instanceipfloat.floating_ip.floating_ip_address

- name: Wait for server to be available
  wait_for:
    host: "{{ instanceipfloat.floating_ip.floating_ip_address }}"
    port: 22
    search_regex: SSH
    timeout: 600
