---

# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server: 
    state: present 
    name: "{{ instance_name }}" 
    image: "{{ instance_image }}"
    key_name: "{{ instance_key_name }}" 
    wait: yes
    flavor: "{{ instance_flavor }}"
    network: int_network
    security_groups: "{{ instance_security_group }}"
    meta:
      group: "{{ instance_group }}"
      deployment_name: "{{ instance_deployment }}"
  register: instanceipaddr

- name: Add floating IP to Servers
  os_floating_ip:
    state: present
    server: "{{ instance_name }}"
    network: ext_network
    wait: true
    timeout: 180
  register: instanceipfloat

- name: Show "{{ instanceipaddr }}" EXT IP
  debug: var=instanceipfloat.floating_ip.floating_ip_address

- name: Wait for server to be available
  wait_for:
    host: "{{ instanceipfloat.floating_ip.floating_ip_address }}"
    port: 22
    search_regex: SSH
    timeout: 600
